-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    user_id serial NOT NULL,
    username character varying(255)[] NOT NULL,
    password_hash character varying(255)[] NOT NULL,
    email character varying(255)[] NOT NULL,
    "profilePicture" pg_snapshot,
    "joinedGroups" integer[],
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public."Groups"
(
    user_id serial NOT NULL,
    "groupName" character varying(255)[] NOT NULL,
    owner_id serial NOT NULL,
    users character varying(512)[] NOT NULL,
    "userAmount" integer
);

CREATE TABLE IF NOT EXISTS public."favoriteMovies"
(
    user_id serial NOT NULL,
    favorite_id serial,
    movie_id serial
);

CREATE TABLE IF NOT EXISTS public."Movies"
(
    movie_id serial NOT NULL,
    name character varying(255)[] NOT NULL,
    media_type character varying(255)[],
    "moviePicture" pg_snapshot,
    vote_count integer,
    PRIMARY KEY (movie_id)
);

ALTER TABLE IF EXISTS public."Groups"
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."favoriteMovies"
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."favoriteMovies"
    ADD CONSTRAINT movie_id FOREIGN KEY (movie_id)
    REFERENCES public."Movies" (movie_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;